name: Generate GitHub Stats Image

on:
  schedule:
    - cron: "0 0 * * *"   # se actualiza una vez al día
  workflow_dispatch:        # permite correrlo manualmente también

jobs:
  github-readme-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: anuraghazra/github-readme-stats-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
